/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Produk Kami',
      items: ['cas'],
      collapsed: false,
      
    },
    {
      type: 'category',
      label: 'Unduh Windows / Office',
      items: ['download_windows', 'microsoft_activation', 'office_c2r_links', 'office_c2r_custom', 'office_for_mac', 'oem_folder'],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Bantuan & Info',
      items: ['command_line_switches', 'bypass-russian-geoblock', 'in-place_repair_upgrade', 'fix-wpa-registry', 'fix_powershell', 'remove_malware', 'clean_install_windows'],
      collapsed: false,
    },
    'news',
    'troubleshoot',
    'credits',
  ],

};

export default sidebars;
